<?php

/*
 * This file is part of huseyinfiliz/language-detection.
 *
 * Copyright (c) 2026 Hüseyin Filiz.
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

/*
 * Country -> ordered list of candidate locales.
 *
 * Keys are ISO 3166-1 alpha-2 codes, uppercase, as returned by the IP lookup. Values
 * are candidate locale codes from `resources/languages.php`, most likely first;
 * `LocaleMatcher` walks the list and applies the first one that is actually installed.
 * If none is installed the request is recorded as a miss and detection falls through to
 * the next method, so a chain never forces a language the forum does not have.
 *
 * Ordering rules that matter:
 *
 *   - The majority language comes first. `CA => ['en', 'fr']`, not `['fr']` -- otherwise a
 *     Canadian visitor on a bilingual forum would be pushed to a minority language.
 *   - `en` is listed explicitly wherever English is a primary language. It is NOT a
 *     universal safety net: core only guarantees that the *configured* `default_locale`
 *     is registered (`LocaleServiceProvider` calls `addLocale($default, 'Default')`, and
 *     English ships as core translations rather than as a language pack), so on a forum
 *     whose default is, say, `tr`, `hasLocale('en')` is false. Entries after `en` are
 *     therefore genuinely reachable and are ordered on purpose.
 *   - Minority and regional languages are kept at the end of a chain so they are only
 *     offered when nothing more likely is installed.
 *
 * Countries whose primary language has no Flarum pack are mapped to a plausible
 * secondary language where one exists, and omitted entirely where guessing would do
 * more harm than falling through. Locales with no country of their own -- `eo`
 * (Esperanto) and `tok` (Toki Pona) -- do not appear here by design; they can only be
 * reached through browser language detection.
 *
 * The RIR extras the dataset can emit for non-country allocations (`EU`, `AP`, `ZZ`)
 * are deliberately absent, so they resolve to no candidates.
 *
 * Not admin-configurable. Maintained by the extension author.
 */

return [
    // Europe
    'AD' => ['ca', 'es', 'fr'],
    'AL' => ['sq'],
    'AT' => ['de'],
    'AX' => ['sv', 'fi'],
    'BA' => ['bs', 'hr', 'sr-Latn'],
    'BE' => ['nl', 'fr', 'de'],
    'BG' => ['bg'],
    'BY' => ['be', 'ru'],
    'CH' => ['de', 'fr', 'it'],
    'CY' => ['el', 'tr'],
    'CZ' => ['cs'],
    'DE' => ['de'],
    'DK' => ['da'],
    'EE' => ['et', 'ru'],
    'ES' => ['es', 'ca', 'gl', 'eu', 'ast'],
    'FI' => ['fi', 'sv'],
    'FO' => ['da'],
    'FR' => ['fr', 'oc', 'br'],
    'GB' => ['en', 'cy'],
    'GG' => ['en'],
    'GI' => ['en', 'es'],
    'GR' => ['el'],
    'HR' => ['hr'],
    'HU' => ['hu'],
    'IE' => ['en', 'ga'],
    'IM' => ['en'],
    'IS' => ['is'],
    'IT' => ['it', 'sc', 'de'],
    'JE' => ['en', 'fr'],
    'LI' => ['de'],
    'LT' => ['lt', 'ru'],
    'LU' => ['fr', 'de'],
    'LV' => ['lv', 'ru'],
    'MC' => ['fr'],
    'MD' => ['ro', 'ru'],
    'ME' => ['sr-Latn', 'bs', 'sq'],
    'MK' => ['mk', 'sq'],
    'MT' => ['en', 'it'],
    'NL' => ['nl'],
    'NO' => ['nb', 'nn'],
    'PL' => ['pl'],
    'PT' => ['pt'],
    'RO' => ['ro', 'hu'],
    'RS' => ['sr-Cyrl', 'sr-Latn'],
    'RU' => ['ru', 'tt'],
    'SE' => ['sv'],
    'SI' => ['sl'],
    'SJ' => ['nb'],
    'SK' => ['sk', 'hu'],
    'SM' => ['it'],
    'UA' => ['uk', 'ru'],
    'VA' => ['it'],
    'XK' => ['sq', 'sr-Latn'],

    // Americas
    'AG' => ['en'],
    'AI' => ['en'],
    'AR' => ['es_AR', 'es'],
    'AW' => ['nl', 'es'],
    'BB' => ['en'],
    'BL' => ['fr'],
    'BM' => ['en'],
    'BO' => ['es'],
    'BQ' => ['nl'],
    'BR' => ['pt-BR', 'pt'],
    'BS' => ['en'],
    'BZ' => ['en', 'es'],
    'CA' => ['en', 'fr'],
    'CL' => ['es'],
    'CO' => ['es'],
    'CR' => ['es'],
    'CU' => ['es'],
    'CW' => ['nl', 'en'],
    'DM' => ['en'],
    'DO' => ['es'],
    'EC' => ['es'],
    'FK' => ['en'],
    'GD' => ['en'],
    'GF' => ['fr'],
    'GL' => ['da'],
    'GP' => ['fr'],
    'GT' => ['es'],
    'GY' => ['en'],
    'HN' => ['es'],
    'HT' => ['fr'],
    'JM' => ['en'],
    'KN' => ['en'],
    'KY' => ['en'],
    'LC' => ['en'],
    'MF' => ['fr'],
    'MQ' => ['fr'],
    'MS' => ['en'],
    'MX' => ['es_MX', 'es'],
    'NI' => ['es'],
    'PA' => ['es'],
    'PE' => ['es'],
    'PM' => ['fr'],
    'PR' => ['es', 'en'],
    'PY' => ['es'],
    'SR' => ['nl'],
    'SV' => ['es'],
    'SX' => ['nl', 'en'],
    'TC' => ['en'],
    'TT' => ['en'],
    'US' => ['en', 'es'],
    'UY' => ['es'],
    'VC' => ['en'],
    'VE' => ['es'],
    'VG' => ['en'],
    'VI' => ['en'],

    // Asia
    'AE' => ['ar', 'en'],
    'AF' => ['fa', 'uzb'],
    'AM' => ['hy', 'ru'],
    'AZ' => ['az', 'ru'],
    'BD' => ['bn', 'en'],
    'BH' => ['ar', 'en'],
    'BN' => ['ms', 'en'],
    'BT' => ['en', 'ne'],
    'CN' => ['zh-Hans', 'ug'],
    'GE' => ['ka', 'ru'],
    'HK' => ['zh-Hant', 'en'],
    'ID' => ['id'],
    'IL' => ['he', 'ar', 'ru'],
    'IN' => ['hi', 'en', 'bn', 'mr', 'te', 'ta', 'kn', 'ml', 'pa', 'ur'],
    'IQ' => ['ar', 'ckb', 'kmr'],
    'IR' => ['fa', 'az', 'ckb'],
    'JO' => ['ar'],
    'JP' => ['ja'],
    'KG' => ['ru', 'kk'],
    'KH' => ['km'],
    'KP' => ['ko'],
    'KR' => ['ko'],
    'KW' => ['ar'],
    'KZ' => ['kk', 'ru'],
    'LB' => ['ar', 'fr'],
    'LK' => ['si', 'ta', 'en'],
    'MM' => ['my'],
    'MO' => ['zh-Hant', 'pt'],
    'MV' => ['en'],
    'MY' => ['ms', 'en', 'zh-Hans', 'ta'],
    'NP' => ['ne'],
    'OM' => ['ar'],
    'PH' => ['fil', 'tl', 'en'],
    'PK' => ['ur', 'en', 'pa'],
    'PS' => ['ar'],
    'QA' => ['ar'],
    'SA' => ['ar'],
    'SG' => ['en', 'zh-Hans', 'ms', 'ta'],
    'SY' => ['ar', 'kmr'],
    'TH' => ['th'],
    'TJ' => ['tg', 'ru'],
    'TM' => ['tk', 'ru'],
    'TR' => ['tr', 'kmr'],
    'TW' => ['zh-Hant'],
    'UZ' => ['uzb', 'ru'],
    'VN' => ['vi'],
    'YE' => ['ar'],

    // Africa
    'AO' => ['pt'],
    'BF' => ['fr'],
    'BI' => ['fr'],
    'BJ' => ['fr'],
    'BW' => ['en'],
    'CD' => ['fr'],
    'CF' => ['fr'],
    'CG' => ['fr'],
    'CI' => ['fr'],
    'CM' => ['fr', 'en'],
    'CV' => ['pt'],
    'DJ' => ['fr', 'ar'],
    'DZ' => ['ar', 'fr', 'kab'],
    'EG' => ['ar'],
    'EH' => ['ar', 'es'],
    'ER' => ['ar', 'en'],
    'ET' => ['en'],
    'GA' => ['fr'],
    'GH' => ['en'],
    'GM' => ['en'],
    'GN' => ['fr'],
    'GQ' => ['es', 'fr', 'pt'],
    'GW' => ['pt'],
    'KE' => ['en'],
    'KM' => ['fr', 'ar'],
    'LR' => ['en'],
    'LS' => ['en'],
    'LY' => ['ar'],
    'MA' => ['ar', 'fr'],
    'MG' => ['fr'],
    'ML' => ['fr'],
    'MR' => ['ar', 'fr'],
    'MU' => ['fr', 'en'],
    'MW' => ['en'],
    'MZ' => ['pt'],
    'NA' => ['en', 'af', 'de'],
    'NE' => ['fr'],
    'NG' => ['en'],
    'RE' => ['fr'],
    'RW' => ['fr', 'en'],
    'SC' => ['fr', 'en'],
    'SD' => ['ar', 'en'],
    'SL' => ['en'],
    'SN' => ['fr'],
    'SO' => ['ar'],
    'SS' => ['en'],
    'ST' => ['pt'],
    'SZ' => ['en'],
    'TD' => ['fr', 'ar'],
    'TG' => ['fr'],
    'TN' => ['ar', 'fr'],
    'TZ' => ['en'],
    'UG' => ['en'],
    'YT' => ['fr'],
    'ZA' => ['en', 'af'],
    'ZM' => ['en'],
    'ZW' => ['en'],

    // Oceania and remaining territories
    'AS' => ['en'],
    'AU' => ['en'],
    'CC' => ['en', 'ms'],
    'CK' => ['en'],
    'CX' => ['en', 'ms'],
    'FJ' => ['en'],
    'FM' => ['en'],
    'GS' => ['en'],
    'GU' => ['en'],
    'IO' => ['en'],
    'KI' => ['en'],
    'MH' => ['en'],
    'MP' => ['en'],
    'NC' => ['fr'],
    'NF' => ['en'],
    'NR' => ['en'],
    'NU' => ['en'],
    'NZ' => ['en'],
    'PF' => ['fr'],
    'PG' => ['en'],
    'PN' => ['en'],
    'PW' => ['en'],
    'SB' => ['en'],
    'SH' => ['en'],
    'TF' => ['fr'],
    'TK' => ['en'],
    'TL' => ['pt', 'id'],
    'TO' => ['en'],
    'TV' => ['en'],
    'UM' => ['en'],
    'VU' => ['fr', 'en'],
    'WF' => ['fr'],
    'WS' => ['en'],
];
