<?php

/*
 * Generated by scripts/build-ip-data.php. Do not edit by hand.
 *
 * `built` is when the dataset was generated; `data_date` is the date the registries
 * say their statistics describe, which is the one worth showing an administrator.
 */

return [
    'built' => '2026-08-24',
    'data_date' => '2026-08-24',
    'source' => 'RIR delegated-extended statistics',
    'registries' => ['afrinic', 'apnic', 'arin', 'lacnic', 'ripencc'],
    'ipv4_records' => 150028,
    'ipv6_records' => 136003,
];
